### PR TITLE
💄style: various style changes for consistency and aesthetics

### PR DESCRIPTION
**Pull request by welpo**

### CODE REVIEW

**Comment by serginogal** [comment]
missing </div> to close the <div class"tags-item" ... >
https://github.com/welpo/tabi/blob/978af11495face1127dc30946989ecac78257207/templates/tags/list.html#L9-L19
```suggestion
{% for term in terms %}
        <div class="tags-item" id="{{ term.name }}">
            <svg class="tags-item-icon" xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24"
                fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
                <path d="M20.59 13.41l-7.17 7.17a2 2 0 0 1-2.83 0L2 12V2h10l8.59 8.59a2 2 0 0 1 0 2.82z"></path>
                <line x1="7" y1="7" x2="7.01" y2="7"></line>
            </svg>
            <a href="{{ term.permalink | safe }}">
                {{ term.name }} ({{ term.pages | length }} post{{ term.pages | length | pluralize }})
            </a>
        </div>
 {% endfor %}
```


Also, since it's a merge for fixing styles, might be good to also fix the social icons when on light mode
https://github.com/welpo/tabi/blob/978af11495face1127dc30946989ecac78257207/sass/parts/_footer.scss#L46-L48

maybe something like this would work
```suggestion
[data-theme="light"] {
      .social {
        &:hover {
          &>img {
            filter: invert(1);
          }
        }
        &>img {
          filter: none;
        }
      }
    }
```

**Review by serginogal — COMMENTED** [review]
missing </div> to close the <div class"tags-item" ... >
https://github.com/welpo/tabi/blob/978af11495face1127dc30946989ecac78257207/templates/tags/list.html#L9-L19
```suggestion
{% for term in terms %}
        <div class="tags-item" id="{{ term.name }}">
            <svg class="tags-item-icon" xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24"
                fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
                <path d="M20.59 13.41l-7.17 7.17a2 2 0 0 1-2.83 0L2 12V2h10l8.59 8.59a2 2 0 0 1 0 2.82z"></path>
                <line x1="7" y1="7" x2="7.01" y2="7"></line>
            </svg>
            <a href="{{ term.permalink | safe }}">
                {{ term.name }} ({{ term.pages | length }} post{{ term.pages | length | pluralize }})
            </a>
        </div>
 {% endfor %}
```


Also, since it's a merge for fixing styles, might be good to also fix the social icons when on light mode
https://github.com/welpo/tabi/blob/978af11495face1127dc30946989ecac78257207/sass/parts/_footer.scss#L46-L48

maybe something like this would work
```suggestion
[data-theme="light"] {
      .social {
        &:hover {
          &>img {
            filter: invert(1);
          }
        }
        &>img {
          filter: none;
        }
      }
    }
```

**Comment by welpo** [comment]
Fixed both issues! Thanks~

**Review by serginogal — APPROVED** [review]
Looks good to me 👍

**Pull request merged**
