### PR TITLE
Support hiding the read time indication on pages

### PR DESCRIPTION
**Pull request by stevenroose**
I'm not sure if there is some kind of documentation on all extra fields that exist. I think there really should be. If there is, let me know where, so I can add this one as part of this MR. Or merge it and add it yourself :) Or reject it ofc :)

### CODE REVIEW

**Comment by welpo** [comment]
I like the idea of adding this feature.

Let's do it similar to other configs, like `katex` or `footnote_backlinks`. That is:

- Allow for global (`config.toml`) or post-specific settings (i.e. in front matter, what you've implemented).
- Add documentation regarding this feature through comments in `config.toml`. Something like this: https://github.com/welpo/tabi/blob/718f477949e20204cb1bc0158f4ebd2c6c38a179/config.toml#L272-L275
- When updating `config.toml` we need to ensure `theme.toml` is also up to date.

Also, I think I prefer the setting being framed in terms of adding, not removing/hiding. For example: `show_reading_time`, and default it to `true` in the Tera template.

The documentation post for all extra settings (in both config / front matter) is coming soon™️. Hopefully this weekend I can get to it.

**Comment by stevenroose** [comment]
Ah yeah I didn't know it was possible to have a default value of true. Will update.

**Comment by stevenroose** [comment]
Fixed. Could you maybe help me understand something? I read something about "sections" and how you can set variables for entire sections. I'd like to have this field set to false by default but true by default for everything in `blog/`. Is that possible? Can I set it false in `/config.toml` and then set it to true in `/content/blog/_index.md`?

**Comment by welpo** [comment]
I've made the following changes:
- Allow page settings to override `config.toml`.
- Hide the separator between elements when reading time is hidden
- Update theme.toml to match config.toml

Regarding sections, you can indeed set variables for them. However, the current code does not check for that. So, in summary, you can set the variable in:
- config
- section
- page

I will update the logic again to handle the section case. In order of priority, settings will be read from post, then section, then config.

By the way, can you elaborate on your specific use-case? Is the intention to have pages like "Privacy policy" or "About me" which do not have the reading time, but to enable it on posts?

**Comment by stevenroose** [comment]
> Regarding sections, you can indeed set variables for them. However, the current code does not check for that. So, in summary, you can set the variable in:
> 
>     * config
> 
>     * section
> 
>     * page
> 
> 
> I will update the logic again to handle the section case. In order of priority, settings will be read from post, then section, then config.
> 
> By the way, can you elaborate on your specific use-case? Is the intention to have pages like "Privacy policy" or "About me" which do not have the reading time, but to enable it on posts?

Oh, I would expect that Zola would do this summarizing of the sections etc and would just expose the final value on the post.. It kinda really should, no?

Yeah, like I have regular pages like "projects", "presentations" that I don't want to show the reading time. Only the `/blog` actual articles I'd want the reading time on.

My use case is live since today @ `https://roose.io/` btw :)

**Comment by welpo** [comment]
>Oh, I would expect that Zola would do this summarizing of the sections etc and would just expose the final value on the post.. It kinda really should, no?

I don't think there's a `get_most_specific_setting` kind of function in Zola. You can get all the page/section/config variables you want, but you have to handle them yourself.

If it does have such an option, I wasted a few hours to overengineer the macro at #128.

By the way, take a look at that PR to see how to enable/disable certain settings (like `show_reading_time`) for entire sections.

Thanks for sharing your use-case/site. It made me realise there's another small issue with the spacing in the meta section: too many spaces between the separators when `minify_html = false` in `config.toml`. Fixing it in next PR!

**Pull request merged**
