### PR TITLE
✨ feat: introduce a 'series of post' feature

### PR DESCRIPTION
**Pull request by ZzMzaw**
## Summary

This PR introduces a series of posts feature.

It is incomplete (draft) so far but objective is to validate some design choices before focusing on documentation, tests and any code improvement (including better comments).

The posts of a serie should be mixed up with other posts when looking at all posts.
The only way I found to efficiently achieve that was by setting the section used to declare the serie transparent.
The impact is that the pages ordering of the serie's section must match the page ordering of the above section.
As a consequence, we cannot use the native sorting mechanism provided by Zola and I assumed the order of the posts of a serie should be reversed from the natural order of the posts.
Nevertheless, I am not sure this assumpation is valid, if there is any better way to do or if we should just introduce a flag to reverse (by default) or not the posts natural order.

This PR introduce two new elements:
1. A page dedicated to the serie which provides the context of the serie and the list of its pages
2. An element added to each page in order to indicate a link with the serie, if any

The page dedicated to the serie has a specific design to glue posts together are they are all linked to the same topic.
In addition, if focuses more on posts' order than on their date or metadata, once again to link all posts together.
Last but not least, it doesn't support pagination on purpose (an error is thrown is pagination is activated in the serie's section) as everything linked to a serie you be visible in the same page and I don't expect to have a lots of posts in a serie.

The element added to each page will only be added if the page is part of a serie.
The style is different from the rest of the article to prevent confusion between the serie info and the article itself.
If exists in two flavor, just a link to the serie or, in addition, a descripton and a list of the serie's articles.
This allow to keep the natural flow of posts with previous/next mechanism.

I provide the only two translations I am able to do but if needed, I can try to translate them with some automatic translator.

Anyway, all choices can be discussed and adapted.
I just tried to propose what I though would fit most.

### Related issue

Discussion started in #256 .

## Changes

Declaring a serie can be done by creating a section with `extra.serie` set to `true`.
This section must not have a `paginate_by` and should be `transparent`.

Most of the tests have been done that way but non transparent section may work as well.

In order to control the serie's info displayed in a page, it is possible to set `extra.serie_page_description` to `none` (default) or to `full`.
The former displays only the title of the serie and a link to it.
The latter displays in addition a description of the serie and a list of its articles.

Last but not least, I introduce a label the page title (in page_header macro) in order to highlight when dealing with a serie section.

I also introduced one minor fix which is linked to this change by colocating some code related to comments in the page.html file.
It has absolutely no visible impact.

### Accessibility

Nothing special but I tried to respect what is already done (semantic HTML, ARIA attributes and colour contrast).
Nevertheless, I don't how to test any accessibility feature on my own.

### Screenshots

My last commit introduces a demo of the feature directly in tabi website which will make understanding easier.
We'll remove this commit before merging.

### Type of change

- [ ] Bug fix (fixes an issue without altering functionality)
- [X] New feature (adds non-breaking functionality)
- [ ] Breaking change (alters existing functionality)
- [ ] UI/UX improvement (enhances user interface without altering functionality)
- [ ] Refactor (improves code quality without altering functionality)
- [ ] Documentation update
- [ ] Other (please describe below)

---

## Checklist

- [ ] I have verified the accessibility of my changes
- [ ] I have tested all possible scenarios for this change
- [ ] I have updated `theme.toml` with a sane default for the feature
- [ ] I have made corresponding changes to the documentation:
- [ ] Updated `config.toml` comments
- [ ] Updated `theme.toml` comments
- [ ] Updated "Mastering tabi" post in English
- [ ] (Optional) Updated "Mastering tabi" post in Spanish
- [ ] (Optional) Updated "Mastering tabi" post in Catalan

### CODE REVIEW

**Comment by ZzMzaw** [comment]
Initial work focused on having a dedicated page for a serie in addition to adding a reference to this page in each article of the serie.

After using it a bit more today, I aligned the style of series with the style of articles as I realised a serie might have some content more content than a simple section should.
A serie page should be considered between a section and page.
Feel free to provide your feedback on that if you think it might not be useful.

I also added a direct link to the serie's post in the title of the serie (once again because the content can be a bit long to read).
It would benefit an icon instead of an sentence but I was not able to make it happen (I am not really good at UI...).

Last but not least, I also allowed extra_feature to be use in a section in addition to a page because a serie may benefit from it (e.g. the go to top button can be useful when there is some content to the serie page).

I would like to validate the current behavior before moving forward when you'll have time to look into it.

Thanks for your help and support.

**Comment by welpo** [comment]
Hey there!

Happy to see progress on this.

Before I take a deep look into the details, could you summarise how a tabi user would add a series of posts?

Step 1: Create a section
Step 2: Set `extra.serie = true`
Step 3: Add posts in that section

Is this right? Is there anything else needed?

Thank you!

**Comment by ZzMzaw** [comment]
Hello,

This is the minimal process.

In this situation, the serie and its pages will only be accessible through direct link to be manually added somewhere as for any other subsection.
In order to mixup serie's child pages with thoose from the section above, it would be better to set `transparent = true` on the serie's section front matter.
I didn't tested it so much but I think the `sort_by` should match the one of the parent section in that case.

Last but not least, a serie section should have some `description` and `content` to feed respectively the link to a serie in a child page and the serie's page itself.

You can have a look to my last commit ([152adf5](https://github.com/welpo/tabi/pull/360/commits/152adf5645c766cfdc6d4cc23fb521e67514b79f)) which is a small demo of the feature.

The `serie_page_description` can be set to `none` for just a link to the serie in the child page (e.g. the second article of the demo serie) or to `full` to get more information in the child page (e.G. the first and third article of the demo serie).

Hope it helps.

Thank you.

**Comment by stalkerGH** [comment]
This feature looks very promising. On my webpage I create the posts which are designed as series so from my point of view idea of series is more than welcome.

**Comment by ZzMzaw** [comment]
@stalkerGH Happy to see this feature can be useful.

Did you get a chance to look at the demo site?
If yes, does the serie's UX fit how you usually deal with series in your webpage.

I tried to make the serie link explicit in the child page instead of melting the serie introduction with the child page itself.
Nevertheless, I am not sure about this decision and I would be glad to get some feedback.

**Comment by stalkerGH** [comment]
> I tried to make the serie link explicit in the child page instead of melting the serie introduction with the child page itself.
> Nevertheless, I am not sure about this decision and I would be glad to get some feedback

Do you mean about THIS frame on the screenshot? In my opinion it's sufficient. It attracts attention and you immediately know you need to expand the list - especially since there is a short introduction and a list of articles below.

tabi-series-concept

**Comment by ZzMzaw** [comment]
I was exactly refering to the frame you pointed in the screenshot.

Nice if it is enough for you.

Thanks for your feedback.

**Comment by welpo** [comment]
Hi again,

Still haven't had time to do an in-depth look at the implementation. I do have some thoughts, though:

The implementation, from a tabi-user standpoint, looks good to me. It's reasonable and simple enough to understand. Great job.

> I assumed the order of the posts of a serie should be reversed from the natural order of the posts

I think both sortings make sense. Not sure which one should be the default, but there should definitely be a variable to configure this (similar to #344).

> it doesn't support pagination on purpose (an error is thrown is pagination is activated in the serie's section) as everything linked to a serie you be visible in the same page and I don't expect to have a lots of posts in a serie

I'm not sure about this. Is there a technical reason for this? I feel like users might want to configure this, same as other sections.

> This allow to keep the natural flow of posts with previous/next mechanism.

I'll think about this. Not sure if we should:

- Override the next/previous links at the bottom with the series posts, not the general section posts
- Add another similar previous/next section, optional, that's specific to the series
- Keep as is

> I also added a direct link to the serie's post in the title of the serie

Not sure about this. When I saw the icon, before reading your comment, I was confused. I'd lean towards no icon at all (I think it's reasonable to expect readers to scroll) or maybe a "Jump to posts" (text only) link.

---

One more question: in the [series listing/overview](https://deploy-preview-360--tabi-demo.netlify.app/blog/serie/), is there a reason you didn't use the `bloglist-container` styling? (Used in main page, blog section, to list posts with a tag…)

--- 

By the way, the singular of "series" is "series", not "serie".

Again, thanks for your time. Hopefully I can look at it more carefully this week~

**Comment by ZzMzaw** [comment]
I fixed the series typo and updated the `jump to articles` button.
I pushed this because I might not be able to work on it again today.

I also started to look into pagination and I think it might be possible because when I do a `get_section` on a section's path, I got the full section without pagination whereas the `section` variable when rendering the section page is properly paginated.

Do you think we can assume this will never be considered as a bug?
I would said no but if it happens, we won't be able to compute the full list of series posts in a series post.

Thanks for your help and feedback.

**Comment by welpo** [comment]
> I also started to look into pagination and I think it might be possible because when I do a `get_section` on a section's path, I got the full section without pagination

I believe this is expected behaviour, and not a bug.

**Comment by ZzMzaw** [comment]
Hello,

I just have a minor doubt.

I understand it could be interesting to let the user control the order of a series' posts in the main series page:
image

But I was wondering what would be your expectation for series' child page:
image

Would you expect it to be reversed starting from 3 (to match the order in the main series page) or should we keep it always in this order and have the 'reverse' option only linked to the main series page?

Many thanks in advance for your feedback.

**Comment by stalkerGH** [comment]
If I may interject: from my point of view, the most natural option is "from oldest to newest." Although I understand that there may be some series that would also work well in the reverse order.

**Comment by ZzMzaw** [comment]
I agree with @stalkerGH regarding natural order of series' pages.

Nevertheless, section's natural order for pages is the other way around in Zola, "from newest to oldest" which makes totally sense for blog posts order.

I though about two options:

### With pagination

If we keep pagination, I would stick with section's natural order for series default as we'll have to use `paginate_reversed` (which is the only way I was able to find to reverse the order of pages with a paginator).
This would allow to make this behavior consistent with people used to Zola pages order.

The default order would then be the same as section's order (i.e from newest to oldest) and so the reverse of what we called natural order for series.
If you want to order pages in this direction instead, you would have to set `series_pages_reversed` to `true` if you don't paginate and add `paginate_reversed` to `true` if you paginate.
Both are required because I was not able to find a way to know if a paginator is reversed or not to compute indexes.

### Without pagination

If we get rid of pagination, we can default to the natural order for series with a `series_pages_order` set to `natural` by default and allow a `reverse` value to get it in the same order as sections.
Keeping pagination would require to add a `paginate_reversed = true` when `series_pages_order = "natural"`  which might be confusing IMHO.


Anyway, I would be glad to get your feedback on this when you have some time.

Thanks in advance.

**Comment by stalkerGH** [comment]
I agree with your conclusions and proposals. It is difficult for me to add anything to these comments, they are complete and provide for all scenarios, I think.

**Comment by welpo** [comment]
Regarding pagination, I don't understand its need. Could we do, without any extra variables:

- On the series main page, where we list all posts with the description on top, follow the order that the user set on this section (without any `extra` variables). To change the sorting, the user will modify `sort_by`. If the user wants a reverse order, they can (1) set `paginate_by` to a non-zero value and (2) set `paginate_reversed` to true.
- On the articles of a series, on the summary, if we list the posts, we should follow the order set above. I assume this either happens automatically (i.e. when doing `for post in section.pages` we get the intended order). If not, we should be able to access the value of `paginate_reversed` for the section, and handle it manually (not ideal).

Am I missing something that makes this approach unreasonable or impossible?

---

By the way, I had this idea: on the series description, we could allow special variables like `$SERIES_POSTS` or `$SERIES_MAIN_PAGE`. When building the description, these would get replaced by the numbered posts, in the first case, or the link to the series main page, in the second.

You don't need to implement this. I'm just writing it here so that I don't forget; I can implement it myself after I give it some more thought.

**Comment by ZzMzaw** [comment]
> Am I missing something that makes this approach unreasonable or impossible?

I may be the one who have missed something.

My goal was to be able to easily reach the serie's natural order we talked about earlier.

From documentation (https://www.getzola.org/documentation/content/section/#reversed-sorting), I was not able to figure out how to reverse section page's order through section's front matter except for pagination (with `paginate_reversed`). The only way to do so without pagination was to use the `reverse`  function.
It means I was not able to reach the serie's natural order by using `sort_by = "date"`.
I tried using `sort_by = "weight"` but I had an error due to the section being transparent (both sort_by date and sort_by weight).
This is why I introduced an extra property to deal with this.

Nevertheless, I did a new test and it seems my first test was wrong... (don't know where I messed up though).
I was able to keep the series's natural order in the series section using `sort_by = "weight"` with `weight` being easily increment for each article and still allow easily integration with the parent section (as series' section is transparent) which uses `sort_by = "date"`.

This makes the configuration so much easier (and the code as well) but it should definitely be documented to allow user to achieve the serie's natural order easily.

There is one point missing about how to compute the index order.
As I won't be able to know what kind of order the user had in mind, would it be ok if I just introduce a `series_index_reversed` parameter?
This would let him decide if the indexes for series' posts should start to 1 and increase or to the number of pages and decrease depending on what fits most her sorting.

I'll start looking into implementing it (in particular for the `paginate_reversed` stuff in the series' page).
Meanwhile, feel free to provide any more feedback.

----

> By the way, I had this idea: on the series description, we could allow special variables like $SERIES_POSTS or $SERIES_MAIN_PAGE. When building the description, these would get replaced by the numbered posts, in the first case, or the link to the series main page, in the second.

Really good idea.

> You don't need to implement this. I'm just writing it here so that I don't forget; I can implement it myself after I give it some more thought.

Sure, I let you think about it and tell me. I can implement it as well if you don't have time to.

I used a short generic sentence to avoid repetitions for people reading all the series' posts one after the other but we can smoothly melt the description in the article's page or propose the two mechanisms (defaulting to one or the other).

Anyway, thanks for the head's up.
I come back to you when I had some time to work on it.

**Comment by welpo** [comment]
> to be able to easily reach the serie's natural order

Hm. The default, without pagination and minimal configuration, would cause the "unnatural" (Zola default) newest-to-oldest, right? Some users might prefer that.

If they want oldest-to-newest (very reasonable), then they can just add this:

```
sort_by = "date"
paginate_by = 99999  # Anything other than 0
paginate_reversed = true
```

I can't see a reason to use `sort_by` to anything other than date (e.g. `weight`), seeing the series posts are to be shown in the main page and the archive page in chronological order. Can you give me an example where a user might prefer to sort by weight rather than date? Or is it a technical need?

> it should definitely be documented to allow user to achieve the serie's natural order easily

Definitely.

> There is one point missing about how to compute the index order

The order by which you list this?:

image

I think we should use the section's settings (as shown above). If the user set it to reverse, we respect that. If they didn't, we also respect that.

**Comment by ZzMzaw** [comment]
> Hm. The default, without pagination and minimal configuration, would cause the "unnatural" (Zola default) newest-to-oldest, right? Some users might prefer that.

Exactly.

> I can't see a reason to use sort_by to anything other than date (e.g. weight), seeing the series posts are to be shown in the main page and the archive page in chronological order. Can you give me an example where a user might prefer to sort by weight rather than date? Or is it a technical need?

As for now, a series is a transparent section, main page and archive page display the serie's parent section which is configured with `sort_by = "date"`. Whatever you put on the series' section is ignored.
`sort_by = "weight"` (or even by `sort_by = "slug"` if you want to hardcode the series page number in the page name such as "01_first_page", "02_second_page", ...) is similar to the snippet you propose with infinite reversed pagination.

Anyway, both would work.

> The order by which you list this?:

Yes

> I think we should use the section's settings (as shown above). If the user set it to reverse, we respect that. If they didn't, we also respect that.

I agree for the order. I was just wondering of the numbers. Depending on the order which will be configured, having `"3 - ZZ", "2 - YY", "1 - XX"` may make more sense than having "1 - ZZ", "2 - YY", "3 - XX".
As indexes comes from a list and I have no other to if it should be considered reverse or not, I would prefer to let the user decide through configuration.

Thanks for your help.
I'll try to propose something by next week.

**Comment by welpo** [comment]
> Depending on the order which will be configured, having `"3 - ZZ", "2 - YY", "1 - XX"` may make more sense than having "1 - ZZ", "2 - YY", "3 - XX".

Ah, I get what you mean!

How about an agonstic solution: using an unordered list instead?

**Comment by ZzMzaw** [comment]
> How about an agonstic solution: using an unordered list instead?

Problem might be the same if I want to propose an index for posts list in the series' main page (as it is today).

I like the ordered way but as you said, unordered may be easier.
I'll look into it and propose something.

**Comment by welpo** [comment]
> Problem might be the same if I want to propose an index for posts list in the series' main page (as it is today).

True. Maybe that's another reason to use the `bloglist-container` with all the default data (date and such) :)

I'm not sure this is the best option, though. I'll see if a better idea pops up.

**Comment by ZzMzaw** [comment]
> Maybe that's another reason to use the bloglist-container with all the default data (date and such) :)

Sure, I have in mind to merge both serieslist back into bloglist.

**Comment by ZzMzaw** [comment]
Hello,

I created a new branch to restart from scratch with all the discussion we had (and fix the typo in the branch name :-)).

Would it be ok if I close this PR and open a new one on the new branch?
Or would you prefer I completely overwrite this branch with the new one?

I still have a bunch of elements to develop, polish and document so I am not sure I'll finish everything this week.
Anyway, I'll keep you posted as soon as I have a ready-to-review branch.

**Comment by welpo** [comment]
> Would it be ok if I close this PR and open a new one on the new branch? Or would you prefer I completely overwrite this branch with the new one?

Both options are fine, so do whatever you prefer :)

**Comment by stalkerGH** [comment]
I simply ask, without any pressure. How is the implementation of the 'series of posts' function going on?

**Comment by welpo** [comment]
> I simply ask, without any pressure. How is the implementation of the 'series of posts' function going on?

I would say it's close to done.

I'm waiting for @ZzMzaw to finish things up. Let me know if you need any help. Documentation and such I can handle no problem.

**Comment by ZzMzaw** [comment]
Sorry for having been so long, the end of the summer was a bit overloaded on my side.

Code is almost ready, I need to finish it and document everything.

I also need a minor PR to zola itself to get some info regarding pagination from get_section function (almost ready, just need to be pushed).

I'll try to open a new PR as soon as possible (hopefully in a couple of weeks).

Thanks for your patience.

**Comment by welpo** [comment]
Glad to hear from you!

No rush at all. I can help with anything you need: docs, code… Just let me know!

**Comment by ZzMzaw** [comment]
I am still cleaning my code a bit but I'll definitively need support on some design for series article navigation and translation as well.
I'll create a new PR as soon as code is clean enough so that you can start looking at it.
Meanwhile, I'll write the associated documentation.
Keep you posted soon.

**Comment by welpo** [comment]
Perfect! Don't hesitate to open a PR with imperfect code, either!

**Comment by ZzMzaw** [comment]
PR #406 opened...
...with imperfect code and no documentation :-)

Let's continue this discussion there.

Thanks again for your support.

**Pull request closed without merging**
