### PR TITLE
✨ feat: add KaTeX support

### PR DESCRIPTION
**Pull request by welpo**

### CODE REVIEW

**Comment by n-WN** [comment]
Has the KaTeX version been updated later?

**Comment by welpo** [comment]
Hey @n-WN!

Yeah, tabi includes the latest KaTeX version, `0.16.2` (updated in #511).

The dependency upgrades are automated through a [GitHub action](https://github.com/welpo/tabi/actions/workflows/upgrade-deps.yml)

**Comment by n-WN** [comment]
I asked about the version because the local editor can display KaTeX while the blog cannot, and the matrix also displays abnormally

https://normalsubgroup.cauchy.top/blog/idek2025-writeup/#2-crt-he-bing

I just don't know how to solve it

**Comment by n-WN** [comment]
> Interesting. Could you try to provide a minimally reproducible example? Something very simple to help me debug, like:
> 
> ```
> +++
> title = "katex bug"
> +++
> 
> $$ … your formulas $$
> ```
> 
> You could also try, instead of `$$` for opening and closing, `\\[` and `\\]` wrapped around the formula(s).

No problem, wait a moment

**Comment by n-WN** [comment]
> Interesting. Could you try to provide a minimally reproducible example? Something very simple to help me debug, like:
> 
> ```
> +++
> title = "katex bug"
> +++
> 
> $$ … your formulas $$
> ```
> 
> You could also try, instead of `$$` for opening and closing, `\\[` and `\\]` wrapped around the formula(s).

#561

**Pull request merged**
