### PR TITLE
🌐 style: improve RTL styling consistency

### PR DESCRIPTION
**Pull request by welpo**
## Summary

Replaces directional CSS properties with logical ones to improve support for right-to-left (RTL) languages across the theme's design. This change improves layout and spacing consistency regardless of text direction.

### Related issues

#262 #270 #272 #274 #368

## Changes

- Replaced directional CSS properties (e.g., margin-right, padding-left) with their logical equivalents (e.g., margin-inline-end, padding-inline-start).
- Simplified some CSS declarations (e.g. h1, h2…).
- Updated layout-related properties to use direction-agnostic alternatives.
- Ensured consistent spacing and alignment for both LTR and RTL text directions.

### Accessibility

Either unaffected or improved for RTL users.

### Type of change

- [ ] Bug fix (fixes an issue without altering functionality)
- [ ] New feature (adds non-breaking functionality)
- [ ] Breaking change (alters existing functionality)
- [X] UI/UX improvement (enhances user interface without altering functionality)
- [ ] Refactor (improves code quality without altering functionality)
- [ ] Documentation update
- [ ] Other (please describe below)

---

## Checklist

- [x] I have verified the accessibility of my changes
- [ ] I have tested all possible scenarios for this change
- [ ] I have updated `theme.toml` with a sane default for the feature
- [ ] I have made corresponding changes to the documentation:
  - [ ] Updated `config.toml` comments
  - [ ] Updated `theme.toml` comments
  - [ ] Updated "Mastering tabi" post in English
  - [ ] (Optional) Updated "Mastering tabi" post in Spanish
  - [ ] (Optional) Updated "Mastering tabi" post in Catalan

### CODE REVIEW

**Comment by welpo** [comment]
Hey @TheAwiteb!

Any chance you could review this PR before I merge?

Everything should look better (more consistent with the LTR tabi styling) on RTL sites.

You should see changes almost everywhere, though most are minor. Codeblocks look much better, same as admonitions and the header.

**Comment by TheAwiteb** [comment]
> Any chance you could review this PR before I merge?

Yes of course, it's 2 AM, I'll check it in the morning 10~11 AM

**Comment by welpo** [comment]
Thank you! There's absolutely no rush :)

**Comment by TheAwiteb** [comment]
Everything looks good, and I like how the arrows are perfectly centered and the dates are moved to the right. But there is one issue with the profile picture, as the screenshots below show.

| Before | After |
|:------:|:-----:| 
|image | image |

---

<small>I only reviewed my website before and after the patch, I don't have an experience with CSS so I didn't review it.</small>

**Comment by welpo** [comment]
> I only reviewed my website before and after the patch, I don't have an experience with CSS so I didn't review it.

Thank you so much! That's exactly what I needed.

I can't reproduce the home page issue on my end, even with the same picture, title and subtitle.

I think it might be related to your extra CSS `blog.css`. Try removing/editing this part:

```css
img#banner-home-img {
    padding: 0.3rem;
}
```

**Pull request merged**
