### PR TITLE
🌐 feat(i18n): overhaul translation system & add languages

### LINKED ISSUE #134: Missing title on `/tags`
# Bug Report

## Environment

Zola version: 0.17.2
tabi commit: https://github.com/welpo/tabi/commit/c79407e6d7ea544a8b337e372309909a58640423

## Expected Behavior
Title should be "Tags" or "All tags" when navigating to `/tags`

## Current Behavior
`/tags` doesn't have a unique title

## Step to reproduce
Navigate to https://welpo.github.io/tabi/tags/

### PR DESCRIPTION
**Pull request by welpo**
<details>
  <summary><strong>TL;DR</strong></summary>
  Overhauled the translation system, loading strings from <code>/i18n</code> TOML files.
</details>

## Overview

This PR aims to significantly improve the localisation system, streamline template structures, and add multiple new languages. It offers a more user-friendly approach to managing translations and addresses several issues related to the readability and maintainability of the codebase.

## Advantages

1. **Ease of Translation Management**: Moved translations to an `/i18n` folder, allowing easier addition and modification.
  
2. **User customisation**: Theme users can easily override or add new translation strings without touching the core logic.

3. **Flexible default language**: Users can set a default language other than English.

4. **Robustness**: Missing translation strings will fall back to English, reducing the chance of errors.

5. **Reduced configuration**: Eliminated the need for `config.extra.languages` and copying/pasting strings into config files.

6. **Modularity**: Enhanced modularity by isolating translation and language-switching logic.

7. **Simplicity**: Simplified the translation macro, making it easier to read and maintain.

8. **Performance**: Potentially minor performance gains by reducing conditional checks.

Also fixes #134.

---

## Changes

1. **New translation system**:
  - Replaced the old translation macro with a more streamlined version that's easier to maintain and extend.
  - Translation strings are now loaded from TOML files within the `/i18n` directory, allowing for easy management.

2. **Updated macro calls**:
  - All existing macro calls have been updated to utilise the new `language_strings` variable, aligning them with the improved translation system. All translated strings are now optional, falling back to English.

3. **Template refactoring**: 
  - Removed `content.html` and integrated its logic into `page.html`. (#141)
  - Moved the language-switcher logic to its own partial template.

4. **UI improvements**: 
  - Fixed a minor spacing issue in the multilingual quotes shortcode.

5. **Languages added**:
  - Chinese (Simplified) (machine translation)
  - French (machine translation)
  - Hindi (machine translation)
  - Italian (machine translation)
  - Japanese (machine translation)
  - Korean (machine translation)
  - Portuguese (European) (reviewed by native speaker)
  - Russian (reviewed by native speaker)
  - Ukranian (machine translation)

## Credit

This overhaul was inspired by Thomas Weitzel's (@thomasweitzel) work on the i18n of his [Zolarwind theme](https://github.com/thomasweitzel/zolarwind).

### CODE REVIEW

**Comment by Jieiku** [comment]
Oh my "All translated strings are now optional, falling back to English."

That alone is absolutely worth pursuing this! I will be following up with doing the same!

**Comment by welpo** [comment]
Finally found a way to do it!

**Comment by Jieiku** [comment]
Regarding the "machine translation" did you find a convenient way to pull the translations into files? or was it copy paste into google translate. (which is how I did most of mine)

**Comment by welpo** [comment]
I asked GPT-4 for the translations, giving it the `en.toml` file, some context, and my requirements.

I validated the output (like the joined 404 keys, or the metadata in context) to make minor adjustments (with GPT-4), and finally I translated the keys on Google Translate and/or DeepL to verify it was reasonable.

**Comment by Jieiku** [comment]
I just tested using this: https://github.com/mgruner/deepl-api-rs
docs: https://mgruner.github.io/deepl-api-rs-docs/deepl/index.html

I signed up for the free account, and it seems to work:

```bash
echo "Recent Posts" | deepl translate --source-language EN --target-language FR | cat -
```

There is a 500,000 monthly character limit, so no idea how quickly I would hit that limit.

For a small site I would think your unlikely to hit the limit very fast. After I implement what you have done here, I would like to try automating some of the translations, possibly via a bash script.

I am going to see if there is a way to automate the use of GPT-4 as well, no idea if they have an API yet.

**Pull request merged**
