### PR TITLE
🐛 fix(i18n): atom feed page direction for RTL langs

### PR DESCRIPTION
**Pull request by TheAwiteb**
Fix https://github.com/welpo/tabi/issues/267

The page will looks like this after this PR

> [!NOTE]
> I change the language from English to Arabic, to see the page in `LTR` and `RTL`

https://github.com/welpo/tabi/assets/59842932/a7575de0-fa67-4c09-aa1d-b4fae813a759

### CODE REVIEW

**Comment by welpo** [comment]
Thank you!

**Comment by welpo** [comment]
I'm curious, did you test if this `auto` option also works for the main template? As an alternative fix to #262.

**Comment by TheAwiteb** [comment]
> I'm curious, did you test if this `auto` option also works for the main template? As an alternative fix to #262.

It's should work, but in Arabic and I think also in other languages we (as individuals) may start a line or something with English word, so this will destroy the entire page.

## If `auto` are risky like this, why I used it here?

Because the start content of the feed page can't be changed. You can change it but you need then edit it on the translation file, I think who will do this he knows what he do

**Comment by welpo** [comment]
Awesome! Thanks for testing and for the clear explanation!! 🫶

**Pull request merged**
